### ISSUE TITLE
svgwrite requires Python '>=3.6' but the running Python is 2.7.16

### ISSUE THREAD

**Issue by HeliosMon** [Findus23/BrachioGraph-Utils#1]
This happens when I try to install svgwrite. 

I have python3 on my raspi, but Python 2.7.16 also

**Comment by Findus23** [comment]
Hi,

I guess you need to use `pip3` instead of `pip` to make sure that it is installed for python3

**Comment by HeliosMon** [comment]
Thanks for the quick answer. It solved the problem.
