### ISSUE TITLE
When I try to convert it picture it doesnt downsize to my grid

### ISSUE THREAD

**Issue by HeliosMon** [Findus23/BrachioGraph-Utils#2]
Is there a trick to so it converts down to my gridsize?

**Comment by Findus23** [comment]
Hi,

This script does not convert any units. So the lines in the output json have the exact same lengths as in the SVG file. 
Converting should not really be needed as this is done by brachiograph itself when printing.
The display command doesn't do this, so you need to tinker around with the `-s` to see all of the image.

**Comment by HeliosMon** [comment]
For some reason he draws the different letters of the sentence I write over each other, when I import the SVG.

So f.e. he wouldnt write "example" but "e" then on top of that "x" then on top that "a".

Do you know why that happens?

**Comment by HeliosMon** [comment]
Found the solutions. In Inkscape I had to combine all the paths to one with Ctrl+K

**Comment by Findus23** [comment]
> For some reason he draws the different letters of the sentence I write over each other, when I import the SVG.

That's for the same reason as explained in https://github.com/Findus23/BrachioGraph-Utils/issues/3#issuecomment-612825344. Often the letters are separate elements with the same coordinates just with transformations to move them around.
